import MenuListComposition from "../layout/button"
import styles from "./vaccins.module.scss"
import logoUrl from '../assets/logo.jpg'
import bgUrl from '../assets/image.jpg'
import { Helmet } from "react-helmet-async"

export default function Vaccins() {
    return (
        <div className={styles.vaccin}>
            <Helmet>
                <title>vaccins Vet Sur Jalles</title>
                <meta name="description" content="clinique vétérinaire vet sur jalles à Saint Jean d'Illac. La clinique vacinne chiens et chats pour :le typhus, le corza, le FLEV, la rage, La maladie de Carré, L’Hépatite de Rubarth, La Parvovirose, La Leptospirose, la Toux du Chenil, La Piroplasmose et la Maladie de Lyme, La Leishmaniose"/>
            </Helmet>
            <div className={styles.menustick}>
                <MenuListComposition/>
            </div>
            <div className={styles.header} style={{ backgroundImage: `url(${bgUrl})` }}>
                <img src={logoUrl} alt="logo" />
                <h1>VACCINS</h1>
            </div>
            <div className={styles.trapeze}></div>
            <div className={styles.content}>
            <h2>LA VACCINATION DU CHAT</h2>
            <h3>La vaccination sert à protéger votre chat de maladies graves qui peuvent laisser des séquelles, voire qui peuvent être mortelles. Les maladies pour lesquelles on vaccine les chats sont les suivantes:</h3>
            <h3>1/ Maladies pour lesquelles on vaccine couramment, dont les vaccins sont vraiment utiles à la santé de votre chat dans notre région. Les protocoles vaccinaux ont évolué ces dernières années pour mieux protéger les animaux en évitant de sur-vacciner. Aujourd’hui, les protocoles reconnus sont de commencer à vacciner dès l’âge de deux mois, puis de faire une deuxième injection à trois mois. Comme les anticorps maternels interagissent avec la réaction immunitaire des vaccins, on conseille une dernière injection de ce protocole de primo-vaccination à 4 mois. Puis en fonction des vaccins, il faudra refaire des rappels tous les ans ou tous les deux ans, voire tous les trois ans.</h3>
            <h3>- Le Typhus : c’est une maladie virale très contagieuse qui touche surtout les chatons non vaccinés. les virus vont attaquer le systéme digestif ( d’où des diarrhées, des vomissements) et la moelle osseuse ( d’où une baisse des globules blancs). Le traitement est symptomatique et la mortalité très élevée. La vaccination est la meilleure protection.</h3>
            <h3>- Le Coryza : c’est une maladie virale qui va provoquer des éternuements, des écoulements du nez et des yeux. Rarement mortelle, elle devient souvent chronique et est très gênante pour le chat. Pas de traitement spécfiique, la vaccination est la meilleure protection.</h3>
            <h3>-Le FELV : c’est une maladie due à un virus proche de celui du SIDA chez l’homme ( aucune contamination possible). Ce virus peut se transmettre de la mère au chaton lors de la gestation, de l’accouchement, de l’allaitement, sinon entre chat adulte lors de morsure, griffure et lors de contact sexuel. Le chat peut rester porteur sain pendant longtemps. Il est responsable d’un syndrome d’immunodéficience et de tumeurs. Pas de traitement spécfiique, la vaccination est la meilleure protection.</h3>
            <h3>2/ Vaccinations légales</h3>
            <h3>- La Rage : c’est une maladie mortelle à 100%, qui se transmet principalement lors de morsure. Il n’y a aucun traitement. Elle est hautement transmissible à l’homme. Il n’y a plus de cas originaire en France et dans les pays européens, tous les cas recensés sont des animaux que des gens ont introduits en France illégalement depuis des pays étrangers où la maladie sévit encore ( Magreb, Pays de l’Est, ...). C’est pourquoi la vaccination antirabique est obligatoire pour les animaux qui viennent de ces pays ou qui y transitent, et comme la maladie est transmissible à l’homme et que aucune vaccination n’est efficace à 100%, le législateur demande en plus une prise de sang pour vérifier que l’animal est bien efficacement vacciné. Le protocole vaccinal varie selon les laboratoires producteurs, pour le vaccin que nous utilisons, il faut faire une première injection après l’âge de trois mois, puis un rappel un an après, puis des rappels tous les trois ans. attention, comme la vaccination anti rabique est une vaccination à caractère légal, les dates anniversaires sont à respecter au jour près ( on peut vacciner quelques jours avant, mais on ne peut pas dépasser ne serait-ce que de 24 heures).</h3>
            <h2>LA VACCINATION DU CHIEN</h2>
            <h3>La vaccination sert à protéger votre chien de maladies graves qui peuvent laisser des séquelles, voire qui peuvent être mortelles. Les maladies pour lesquelles on vaccine les chiens sont les suivantes:</h3>
            <h3>1/ Maladies pour lesquelles on vaccine couramment, dont les vaccins sont vraiment utiles à la santé de votre chien dans notre région. Les protocoles vaccinaux ont évolué ces dernières années pour mieux protéger les animaux en évitant de sur-vacciner. Aujourd’hui, les protocoles reconnus sont de commencer à vacciner dès l’âge de deux mois, puis de faire une deuxième injection à trois mois. Comme les anticorps maternels interagissent avec la réaction immunitaire des vaccins, on conseille une dernière injection de ce protocole de primo-vaccination à 4 mois. Puis en fonction des vaccins, il faudra refaire des rappels tous les ans ou tous les deux ans, voire tous les trois ans.</h3>
            <h3>- La maladie de Carré : c’est une maladie virale qui touche de nombreux organes ( intestin, appareil respiratoire, appareil urinaire). Les symptômes sont variés : fièvre, abattement, vomissements, diarrhées, toux, jetage nasal, difficultés respiratoires, atteintes oculaires, troubles neurologiques, troubles cutanés. Il n’y a pas de traitement spécifique pour cette maladie mortelle. Le seul moyen de lutter contre cette maladie est la vaccination.</h3>
            <h3>- L’Hépatite de Rubarth : il s’agit d’un virus qui attaque les cellules du foie. Les symptômes sont de la fièvre, des troubles digestifs ( vomissements, diarrhée), abattement, anorexie, douleur abdominale, troubles de la coagulation sanguine et des gros ganglions. Il est possible que le chien développe des complications ophtalmologiques et rénales. Cette maladie est aussi très dangereuse et il n’y a pas de traitement spécifique. Le seul moyen de lutte est là aussi la vaccination.</h3>
            <h3>- La Parvovirose : Il s’agit là encore d’une maladie virale. Le virus attaque les cellules épithéliales de l’intestin et va provoquer des diarrhées hémorragiques, des vomissements, de la fièvre, de la déshydratation. De plus, ce virus attaque les cellules souches de la moelle osseuse et va faire diminuer les globules blancs. Le vétérinaire va faire des soins pour corriger les effets de cette maladie qui peut atteindre 30% de mortalité. La vaccination bien faite est un excellent moyen de protection.</h3>
            <h3>- La Leptospirose : c’est une bactérie qui est responsable de cette maladie, bactérie qui peut se transmettre à l’homme, il faut donc faire très attention quand on manipule un chien atteint. Cette maladie touche les reins et le foie, provoquant une insuffisance rénale aigüe et une hépatite, très souvent mortelle. Il existe près de 800 variétés de leptospires. Les nouveaux vaccins agissent sur 4 d’entre elles, celles que l’on retrouve le plus fréquemment.</h3>
            <h3>- la Toux du Chenil : c’est une maladie causée par des bactéries et des virus, qui vont provoquer de la toux et des éternuements. Extrêmement contagieuse, cette maladie n’est pas mortelle, mais elle peut être longue à soigner. Cette vaccination vous sera demandée si vous laissez votre chien dans une pension.</h3>
            <h3>2/ Vaccinations légales</h3>
            <h3>- La Rage : c’est une maladie mortelle à 100%, qui se transmet principalement lors de morsure. Il n’y a aucun traitement. Elle est hautement transmissible à l’homme. Il n’y a plus de cas originaire en France et dans les pays européens, tous les cas recensés sont des animaux que des gens ont introduits en France illégalement depuis des pays étrangers où la maladie sévit encore ( Magreb, Pays de l’Est, ...). C’est pourquoi la vaccination antirabique est obligatoire pour les animaux qui viennent de ces pays ou qui y transitent, et comme la maladie est transmissible à l’homme et que aucune vaccination n’est efficace à 100%, le législateur demande en plus une prise de sang pour vérifier que l’animal est bien efficacement vacciné. Le protocole vaccinal varie selon les laboratoires producteurs, pour le vaccin que nous utilisons, il faut faire une première injection après l’âge de trois mois, puis un rappel un an après, puis des rappels tous les trois ans. attention, comme la vaccination anti rabique est une vaccination à caractère légal, les dates anniversaires sont à respecter au jour près ( on peut vacciner quelques jours avant, mais on ne peut pas dépasser ne serait-ce que de 24 heures).</h3>
            <h3>3/ Autres vaccinations</h3>
            <h3>- La Piroplasmose et la Maladie de Lyme : ce sont des maladies transmises par piqûres de tiques, qui sont graves ( les animaux peuvent avoir des séquelles) voire mortelles. Grace à l’amélioration des traitements anti tiques, ce sont des maladies que l’on voit peu maintenant. Si vous désirez vacciner vos chiens contre ces maladies, merci de nous le dire lors de la prise de rendez-vous, nous commanderons le vaccin pour vous.</h3>
            <h3>- La Leishmaniose : maladie transmise par les phlébotomes ( moustiques) qui sévit fortement dans le sud-est de la France, mais qui n’est pas encore présente dans notre région. Si vous prévoyez d’y amener votre chien en période d’activité des moustiques, signalez le nous, nous pourrons prévoir un protocole vaccinal adapté.</h3>
            </div>
        </div>
    )
}